-- Exporter.lua
-- Converts the timeline into Roblox-native formats:
--   * KeyframeSequence per rig (importable into the Animation Editor)
--   * A self-contained "Cutscene.lua" script that replays everything at runtime

local Constants  = require(script.Parent.Parent.Constants)
local Keyframes  = require(script.Parent.Keyframes)
local RigManager = require(script.Parent.RigManager)

local Exporter = {}

----------------------------------------------------------------
-- Rig animation export
----------------------------------------------------------------

local function bakeKeyframeSequence(track, fps, length)
    local seq = Instance.new("KeyframeSequence")
    seq.Name = ("ArenaAnim_%s"):format(track.name)
    seq.Loop = false

    local frames    = math.max(2, math.floor(length * fps))
    local motors    = RigManager.findMotors(track.target)
    local motorByName = {}
    for _, m in ipairs(motors) do motorByName[m.Name] = m end

    for i = 0, frames do
        local t = (i / frames) * length
        local kf = Instance.new("Keyframe")
        kf.Name = "Keyframe"
        kf.Time = t

        for motorName, keys in pairs(track.motors) do
            local motor = motorByName[motorName]
            if motor and #keys > 0 then
                local cf = Keyframes.evaluate(keys, t)
                if cf then
                    local pose = Instance.new("Pose")
                    pose.Name        = motor.Part1.Name
                    pose.CFrame      = cf
                    pose.Weight      = 1
                    pose.EasingStyle = Enum.PoseEasingStyle.Cubic
                    pose.EasingDirection = Enum.PoseEasingDirection.InOut

                    -- KeyframeSequences expect a hierarchy mirroring the rig.
                    local rootPose = Instance.new("Pose")
                    rootPose.Name  = motor.Part0.Name
                    rootPose.Weight= 0
                    pose.Parent    = rootPose
                    rootPose.Parent= kf
                end
            end
        end
        kf.Parent = seq
    end

    return seq
end

function Exporter.exportRig(state, track)
    return bakeKeyframeSequence(track, state.data.fps, state.data.length)
end

----------------------------------------------------------------
-- Full cutscene export
----------------------------------------------------------------

local function serializeCFrame(cf)
    local x,y,z, m11,m12,m13, m21,m22,m23, m31,m32,m33 = cf:GetComponents()
    return string.format(
        "CFrame.new(%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f)",
        x,y,z, m11,m12,m13, m21,m22,m23, m31,m32,m33
    )
end

local function serializeValue(v)
    local typ = typeof(v)
    if typ == "number"  then return tostring(v) end
    if typ == "boolean" then return tostring(v) end
    if typ == "string"  then return string.format("%q", v) end
    if typ == "Vector3" then return ("Vector3.new(%f,%f,%f)"):format(v.X, v.Y, v.Z) end
    if typ == "Color3"  then return ("Color3.fromRGB(%d,%d,%d)"):format(v.R*255, v.G*255, v.B*255) end
    if typ == "CFrame"  then return serializeCFrame(v) end
    return "nil"
end

local function dumpKeys(keys)
    local out = {"{"}
    for _, k in ipairs(keys) do
        table.insert(out, string.format(
            "{time=%f,value=%s,easing=%q},",
            k.time, serializeValue(k.value), k.easing or "Cubic"
        ))
    end
    table.insert(out, "}")
    return table.concat(out)
end

function Exporter.exportCutscene(state)
    local data = state.data
    local folder = Instance.new("Folder")
    folder.Name = "ArenaCutscene"

    -- Bake each rig track into a KeyframeSequence
    local rigsFolder = Instance.new("Folder")
    rigsFolder.Name = "Animations"
    rigsFolder.Parent = folder
    for _, track in ipairs(data.tracks) do
        if track.kind == Constants.TRACK_KIND.Rig and track.target then
            local seq = Exporter.exportRig(state, track)
            seq.Parent = rigsFolder
        end
    end

    -- Camera / Audio / Subtitle / Effect data goes into one runnable script
    local script = Instance.new("Script")
    script.Name  = "Cutscene"

    local lines = {
        "-- Generated by Arena Animator " .. Constants.VERSION,
        "-- Place this script anywhere; require / call _G.PlayArenaCutscene() to play.",
        "local TweenService = game:GetService('TweenService')",
        "local RunService   = game:GetService('RunService')",
        "local Players      = game:GetService('Players')",
        "local SoundService = game:GetService('SoundService')",
        "",
        "local LENGTH = " .. data.length,
        "local FPS    = " .. data.fps,
        "",
        "local cameraKeys    = " .. dumpKeys((function()
            for _, t in ipairs(data.tracks) do
                if t.kind == Constants.TRACK_KIND.Camera then return t.keys end
            end
            return {}
        end)()),
        "local cameraFovKeys = " .. dumpKeys((function()
            for _, t in ipairs(data.tracks) do
                if t.kind == Constants.TRACK_KIND.Camera then return t.fovKeys end
            end
            return {}
        end)()),
        "",
        "-- Audio clips",
        "local audio = {}",
    }

    for _, t in ipairs(data.tracks) do
        if t.kind == Constants.TRACK_KIND.Audio then
            table.insert(lines, string.format(
                "table.insert(audio, {soundId=%q, start=%f, length=%f, volume=%f, pitch=%f, trimIn=%f})",
                t.soundId or "", t.start, t.length, t.volume, t.pitch, t.trimIn
            ))
        end
    end

    table.insert(lines, "")
    table.insert(lines, "-- Subtitles")
    table.insert(lines, "local subtitles = {}")
    for _, t in ipairs(data.tracks) do
        if t.kind == Constants.TRACK_KIND.Subtitle then
            for _, c in ipairs(t.clips) do
                table.insert(lines, string.format(
                    "table.insert(subtitles, {time=%f,length=%f,text=%q,fx=%q})",
                    c.time, c.length, c.text or "", c.fx or "Fade"
                ))
            end
        end
    end

    -- Player function appended verbatim
    table.insert(lines, [[

local function lerpCFrame(a, b, t) return a:Lerp(b, t) end

local function evalKeys(keys, time)
    if #keys == 0 then return nil end
    if time <= keys[1].time then return keys[1].value end
    if time >= keys[#keys].time then return keys[#keys].value end
    for i = 1, #keys-1 do
        local a, b = keys[i], keys[i+1]
        if time >= a.time and time <= b.time then
            local span = b.time - a.time
            if span <= 0 then return b.value end
            local raw = (time - a.time) / span
            local style = Enum.EasingStyle[a.easing] or Enum.EasingStyle.Cubic
            local alpha = TweenService:GetValue(raw, style, Enum.EasingDirection.InOut)
            if typeof(a.value) == "CFrame" then return lerpCFrame(a.value, b.value, alpha) end
            return a.value + (b.value - a.value) * alpha
        end
    end
end

function _G.PlayArenaCutscene()
    local cam = workspace.CurrentCamera
    cam.CameraType = Enum.CameraType.Scriptable

    -- Subtitle GUI
    local player = Players.LocalPlayer
    local gui, label
    if player then
        gui = Instance.new("ScreenGui")
        gui.IgnoreGuiInset = true
        gui.ResetOnSpawn = false
        gui.Parent = player:WaitForChild("PlayerGui")
        label = Instance.new("TextLabel")
        label.Size = UDim2.new(0.8, 0, 0, 60)
        label.Position = UDim2.new(0.1, 0, 0.78, 0)
        label.BackgroundTransparency = 0.4
        label.BackgroundColor3 = Color3.new()
        label.TextColor3 = Color3.new(1,1,1)
        label.Font = Enum.Font.Gotham
        label.TextSize = 22
        label.Text = ""
        label.Parent = gui
    end

    -- Spawn audio
    local sounds = {}
    for _, a in ipairs(audio) do
        local s = Instance.new("Sound")
        s.SoundId = a.soundId
        s.Volume  = a.volume
        s.PlaybackSpeed = a.pitch
        s.Parent = SoundService
        sounds[#sounds+1] = {sound=s, info=a, played=false}
    end

    local start = os.clock()
    local conn
    conn = RunService.Heartbeat:Connect(function()
        local t = os.clock() - start
        if t >= LENGTH then
            for _, s in ipairs(sounds) do s.sound:Stop() s.sound:Destroy() end
            if gui then gui:Destroy() end
            cam.CameraType = Enum.CameraType.Custom
            conn:Disconnect()
            return
        end

        local cf = evalKeys(cameraKeys, t)
        if cf then cam.CFrame = cf end
        local fov = evalKeys(cameraFovKeys, t)
        if fov then cam.FieldOfView = fov end

        for _, s in ipairs(sounds) do
            if not s.played and t >= s.info.start then
                s.played = true
                s.sound.TimePosition = s.info.trimIn
                s.sound:Play()
            end
        end

        if label then
            local active
            for _, sub in ipairs(subtitles) do
                if t >= sub.time and t <= sub.time + sub.length then active = sub break end
            end
            if active then
                label.Text = active.text
                local localT = (t - active.time) / active.length
                if active.fx == "Fade" then
                    label.TextTransparency = math.abs(localT*2 - 1)
                elseif active.fx == "Typewriter" then
                    local n = math.floor(#active.text * math.min(localT*2, 1))
                    label.Text = active.text:sub(1, n)
                else
                    label.TextTransparency = 0
                end
            else
                label.Text = ""
            end
        end
    end)
end
]])

    script.Source = table.concat(lines, "\n")
    script.Parent = folder

    return folder
end

return Exporter
